### ISSUE TITLE
App Crashing whenever attempting simple usage of `RollbarContext`

### ISSUE THREAD

**Issue by JackCurrie** [rollbar/rollbar-react#22] opened 2021-11-11 22:50 UTC
Hello all,

I am working on my initial rollbar integration, so I apologise if this is just a silly misunderstanding or if this is the incorrect forum.

I was looking to give my rollbar errors more context by route in my react app. I started adding `RollbarContext` wrappers with simple `context` strings in them to the routes, but I was getting an error whenever I navigated to these routes.

Below, I have an example of the simplest possible usage of this with our react app. It is in the root component, wrapping all of the routes, inside a correctly initialized `Provider`. ( I am 100% sure that the provider is initialized correctly) It gives the error from the following screenshot now whenever I open the app.

<hr>

<img width="640" alt="Screen Shot 2021-11-11 at 2 41 49 PM" src="https://user-images.githubusercontent.com/15962247/141380164-f044746c-65a1-49c5-ac97-26014f643206.png">

<img width="1091" alt="Screen Shot 2021-11-11 at 2 44 21 PM" src="https://user-images.githubusercontent.com/15962247/141380174-98a231ae-c1dd-4b9e-bdce-211d8f4934e6.png">

<hr>

Anybody here have any insight as to what I may be doing incorrectly here?

Thank you so much for your help!

**Comment by JackCurrie** [comment] 2021-11-12 05:41
<img width="1900" alt="Screen Shot 2021-11-11 at 9 39 57 PM" src="https://user-images.githubusercontent.com/15962247/141415922-7354abd0-741c-4dde-812e-23b8f5fc945f.png">


Further details which may be helpful--I am not able to use the `useRollbarContext` method either. It is claiming that `useEffect` is not available internally in the library. Is it possible that I have something misconfigured?

Just very confused, as I am following the docs step-by-step.

**Comment by JackCurrie** [comment] 2021-11-12 06:06
https://github.com/rollbar/rollbar-react/blob/e7c601d7133c945f946f4f9d3a1abdce29b18b8d/src/hooks/use-rollbar-context.js#L1-L21

It doesn't appear that `useEffect` is defined anywhere in this file.

**Comment by agnislav** [comment] 2021-11-15 13:07
The same issue. Is this repo supported? ))

**Comment by u-ashish** [comment] 2021-12-28 21:59
+1 -- I noticed the same when playing around with this on a react project with a friend on a dead simple application.

**Comment by ijsnow** [comment] 2022-02-16 03:08
Looks like this is two separate issues:

1. Original issue (haven't looked into the cause yet)
2. The forgotten import for `useEffect` in https://github.com/rollbar/rollbar-react/blob/main/src/hooks/use-rollbar-context.js [(fixed here)](https://github.com/rollbar/rollbar-react/pull/34)

**Comment by ijsnow** [comment] 2022-03-08 22:29
I wasn't able to reproduce the issue you originally mentioned. However I did produce a working example using `RollbarContext` in #44 .

The second issue I mentioned above has been fixed and released. Please checkout the example in the PR above and give it another try. If it's still not working, please put together a minimal repo and open another issue with the link to it. Going to close this since it alludes to two separate issues.

**Closed by ijsnow** 2022-03-08 22:29 UTC
Labels: bug
